#!/bin/bash

#set -x
#echo ">>>>>>> $0 $* <<<<<<<"

VAR_DIR=/var/lib/lxc-nextdom
ETC_DIR=/etc/lxc-nextdom
LXC_DIR=/var/lib/lxc


case "$1" in
  remove)
    #
  ;;

  purge)
    if [ -f ${VAR_DIR}/list ] ; then
      for container in $(cat ${VAR_DIR}/list) ; do
        isrunning=$(lxc-info -n ${container} --state |awk -F" " '{print $2}')
        if [ ${isrunning} == 'RUNNING' ] ; then
          lxc-stop -n ${container}
        fi
        lxc-destroy -n ${container}
      done
    fi
    #
    if [ -d ${VAR_DIR} ] ; then \rm -rf ${VAR_DIR} ; fi
  ;;

  upgrade)
  ;;

esac


\rm -rf /var/lib/lxc/lxc-nextdom
